# 标准训练模式配置

# 基本配置
name: "sbs_standard_training"
description: "SBS标准监督训练"
version: "1.0.0"

# 数据配置
train_data_path: "data/standard/train"
val_data_path: "data/standard/val"
test_data_path: "data/standard/test"

# 模型配置
model_type: "sbs_model"
model_config:
  input_size: 128
  hidden_size: 256
  output_size: 5  # 5个点的预测
  num_layers: 3
  dropout: 0.2

# 优化器配置
optimizer:
  type: "adam"
  learning_rate: 0.001
  weight_decay: 0.0001

# 学习率调度器
use_lr_scheduler: true
scheduler_type: "step"
lr_step_size: 10
lr_gamma: 0.1

# 训练参数
batch_size: 32
epochs: 100
val_interval: 1
save_interval: 5
early_stop: 10
num_workers: 4
shuffle: true

# 设备配置
device: "cuda"  # 或 "cpu"

# 日志和检查点
log_dir: "logs/standard"
checkpoint_dir: "checkpoints/standard"

# 评估配置
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]
  save_predictions: true
  visualization: true 