# SBS系统配置模板
# 请根据实际环境修改相关配置

# 系统环境配置
environment: development  # 可选: development, production, testing
debug: true
log_level: INFO  # 可选: DEBUG, INFO, WARNING, ERROR, CRITICAL

# 设备配置
device:
  use_gpu: true
  num_workers: 4

# 模型配置
model:
  path: models/llava-sbs
  batch_size: 32
  type: transformer
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

# API配置
api:
  tradingview_key: your_tradingview_api_key_here
  discord_webhook: your_discord_webhook_url_here

# 数据库配置
database:
  host: localhost
  port: 5432
  name: sbs_system
  user: your_db_username
  password: your_db_password

# 缓存配置
cache:
  redis_host: localhost
  redis_port: 6379
  redis_password: null  # 如果没有密码则保持null

# 网络配置
network:
  mirror_url: https://api.example.com
  verify_ssl: true
  timeout: 30

# 安全配置
security:
  secret_key: your_secret_key_here
  jwt_secret: your_jwt_secret_here
  encryption_key: your_encryption_key_here

# 监控配置
monitoring:
  prometheus_port: 9090
  grafana_port: 3000

# 备份配置
backup:
  path: /path/to/backup
  retention_days: 7

# 通知配置
notification:
  enabled: true
  level: INFO
  email_host: smtp.qq.com
  email_port: 587
  email_use_tls: true
  email_host_user: your_email@qq.com
  email_host_password: your_email_auth_code
  email_from: your_email@qq.com
  email_to:
    - recipient1@example.com
    - recipient2@example.com
  email_subject_prefix: "[SBS系统]"

# 训练配置
training:
  gpu_settings:
    device_ids: [0]
    memory_limit: 0.8
    mixed_precision: true
  baseline_validation:
    enabled: true
    interval: 1000
    metrics:
      - accuracy
      - f1_score
  initial_training:
    epochs: 10
    learning_rate: 0.001
    warmup_steps: 100
  validation:
    batch_size: 32
    frequency: 500
  data:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
  optimizer:
    type: adam
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
  process:
    save_checkpoint_steps: 1000
    log_frequency: 100
    early_stopping_patience: 5

# 信号配置
signal:
  thresholds:
    confidence: 0.8
    strength: 0.7
    volume: 1.5
  min_interval: 24  # 小时 